export const ICONS = {
	akechi: 'Akechi',
	ann: 'Ann',
	annoying: 'Annoying Character',
	futaba: 'Futaba',
	haru: 'Haru',
	hifumi: 'Hifumi',
	kawakami: 'Kawakami',
	makoto: 'Makoto',
	morgana: 'Morgana',
	takemi: 'Takemi',
	ryuji: 'Ryuji',
	sae: 'Sae',
	sojiro: 'Sojiro',
	twins: 'Twins',
	yuzuke: 'Yuzuke',
	default: 'Default',
};
